DROP DATABASE PETS;

CREATE DATABASE PETS;

USE PETS;

CREATE TABLE USUARIO(
    ID_USUARIO BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(200),
    EMAIL VARCHAR(200) NOT NULL UNIQUE,
    SENHA VARCHAR(200),
    DATA_CRIACAO DATE NOT NULL,
    DATA_ENCERRAMENTO DATE,
    STATUS VARCHAR(7) NOT NULL
);

CREATE TABLE CLIENTE(
    ID_CLIENTE BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(200),
    DATA_NASCIMENTO DATE NOT NULL,
    CPF VARCHAR(200) UNIQUE,
    REGISTRO_GERAL VARCHAR(200) UNIQUE,
    TELEFONE VARCHAR(20),
    EMAIL VARCHAR(200),  
    ID_ENDERECO INT,
    STATUS VARCHAR(7) NOT NULL
);

CREATE TABLE ANIMAL(
    ID_ANIMAL BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(200),
    PESO FLOAT,
    RACA VARCHAR(200) NOT NULL,
    IDADE INT,
    SEXO VARCHAR(200) NOT NULL,
    STATUS VARCHAR(7) NOT NULL
);

CREATE TABLE ENDERECO(
    ID_ENDERECO BIGINT AUTO_INCREMENT PRIMARY KEY,
    CEP VARCHAR(200),
    CIDADE VARCHAR(200),
    ESTADO VARCHAR(200),
    BAIRRO VARCHAR(200),
    RUA VARCHAR(200),
    NUMERO VARCHAR(200),
    COMPLEMENTO VARCHAR(200),
    STATUS VARCHAR(7) NOT NULL
);

CREATE TABLE MEDICAMENTO(
    ID_MEDICAMENTO BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(200),
    PRINCIPIO_ATIVO VARCHAR(200),
    FABRICANTE VARCHAR(200),
	STATUS VARCHAR(7) NOT NULL 
);

CREATE TABLE PRONTUARIO(
    ID_PRONTUARIO BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_ANIMAL BIGINT,
    DATA_CRIACAO DATE NOT NULL,
    TEMPERATURA FLOAT,
    FREQUENCIA_CARDIACA INT,    
    SINTOMAS VARCHAR(2000),
    DIAGNOSTICO_PROVAVEL VARCHAR(2000),
    DIAGNOSTICO_DEFINITIVO VARCHAR(2000),
    STATUS VARCHAR(7) NOT NULL
);

CREATE TABLE LISTA_CLIENTE_ANIMAL(
    ID_LISTA_CLIENTE_ANIMAL INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE BIGINT,
    ID_ANIMAL BIGINT,
    DATA_CRIACAO DATE NOT NULL
);

CREATE TABLE LISTA_MEDICAMENTO_PRONTUARIO(
    ID_LISTA_MEDICAMENTO_PRONTUARIO INT AUTO_INCREMENT PRIMARY KEY,
    ID_MEDICAMENTO BIGINT,
    ID_PRONTUARIO BIGINT,
    DATA_CRIACAO DATE NOT NULL
);

CREATE TABLE AGENDAMENTO(
    ID_AGENDAMENTO BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO BIGINT NOT NULL,
    ID_CLIENTE BIGINT NOT NULL,
    ID_ANIMAL BIGINT NOT NULL,
    DATA_AGENDAMENTO DATE NOT NULL,
    HORA_AGENDAMENTO TIME NOT NULL,
    STATUS VARCHAR(9) NOT NULL
);

CREATE TABLE ACESSO(
    ID_ACESSO BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO BIGINT NOT NULL,
    ACESSO_ADMINISTRADOR VARCHAR(3) NOT NULL,
    ACESSO_MEDICO_VETERINARIO VARCHAR(3) NOT NULL,
    ACESSO_ATENDENTE VARCHAR(3) NOT NULL    
);

insert into USUARIO (NOME,EMAIL,SENHA,DATA_CRIACAO,DATA_ENCERRAMENTO,STATUS) 
values ('Pets','pets@gmail.com','qwe123',NOW(),'3000-12-31','Ativo');

insert into ACESSO (ID_USUARIO,ACESSO_ADMINISTRADOR,ACESSO_MEDICO_VETERINARIO,ACESSO_ATENDENTE) 
values (1,'Sim','Sim','Sim');